name: pdbx
description: A robust Dart library for managing encrypted databases in the PDBX format. Designed for secure storage of passwords, notes, and other sensitive records with group support.
version: 1.1.0
homepage: https://passblock.ru
repository: https://github.com/smiledll/pdbx
issue_tracker: https://github.com/smiledll/pdbx/issues

environment:
  sdk: ^3.10.0

dependencies:
  argon2_ffi_base: ^1.1.1
  cryptography: ^2.9.0
  json_annotation: ^4.10.0
  meta: ^1.18.1
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.11.1
  json_serializable: ^6.12.0
  lints: ^6.1.0
  test: ^1.29.0
